import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "opsboard");

function fail(message) {
  console.error("release: " + message);
  process.exit(1);
}

function run(command, args) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit" });
  if (result.status !== 0) fail(command + " " + args.join(" ") + " failed");
}

function read(rel) {
  return readFileSync(join(root, rel), "utf8");
}

["index.html", "styles.css", "app.js", "README.md", "CHANGELOG.md", "LICENSE", ".nojekyll", "tests/qa.html", "tests/qa.js", "docs/qa/QA-REPORT.md"]
  .forEach((rel) => {
    if (!existsSync(join(root, rel))) fail("missing required file " + rel);
  });

run("node", ["--check", "app.js"]);
run("node", ["--check", "tests/qa.js"]);

const index = read("index.html");
if (!/styles\.css\?v=/.test(index)) fail("index.html missing versioned styles.css");
if (!/app\.js\?v=/.test(index)) fail("index.html missing versioned app.js");
if (/src="\/src\/|\/node_modules\//.test(index)) fail("index.html references a build-only path");

const app = read("app.js");
const versionMatch = app.match(/APP_VERSION = "([0-9]+\.[0-9]+\.[0-9]+)"/);
if (!versionMatch) fail("APP_VERSION not found");
if (!read("CHANGELOG.md").includes("## [" + versionMatch[1] + "]")) {
  fail("CHANGELOG.md has no entry for " + versionMatch[1]);
}
if (/console\.(log|debug)\(|debugger;|FIXME/.test(app)) fail("debug marker found in app.js");

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

["index.html", "styles.css", "app.js", "README.md", "CHANGELOG.md", "LICENSE", ".nojekyll"].forEach((rel) => {
  cpSync(join(root, rel), join(outDir, rel));
});
["tests", "docs/qa"].forEach((rel) => {
  cpSync(join(root, rel), join(outDir, rel), { recursive: true });
});

writeFileSync(join(outDir, "BUILD.txt"), "Techniek OpsBoard Pro " + versionMatch[1] + "\nGenerated by pnpm run release.\n", "utf8");
console.log("release: validated static app and refreshed opsboard/ for v" + versionMatch[1]);
